[providers]
python = "3.12"

[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements-simple.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
